### ISSUE TITLE
pgfplots error - unbalanced columns

### ISSUE THREAD

**Issue by TronicZomB** [TronicZomB/LaTex-Tutorials#1]
./09.tex:37: Package pgfplots Error: input table '<inline_table>' has an unbala
nced number of columns in row '2' (expected '8' cols; got '3'). Maybe the input
 table is corrupted? If you need unbalanced data, consider using 'nan' in empty
 cells (perhaps combined with 'unbounded coords=jump').

**Comment by Xychun** [comment]
Solution?
